//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました. 
//     ランタイム 버전:4.0.30319.18444
//
//     このファイルへの변경は, 以下の状況下で不正な動作の原因になったり, 
//     コードが再生成されるときに損失したりします. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace gvtrademap_cs.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを검색するための, 厳密に型지정된リソース クラスです. 
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを사용して自動生成されました. 
    // メンバーを追加または삭제するには, .ResX ファイルを編集して, /str オプションと共に
    // ResGen を実行し直すか, または VS プロジェクトをビルドし直します. 
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで사용されているキャッシュされた ResourceManager インスタンスを返します. 
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gvtrademap_cs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型지정된このリソース クラスを사용して, 전부の검색リソースに対し, 
        ///   현재のスレッドの CurrentUICulture プロパティをオーバーライドします. 
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap country00 {
            get {
                object obj = ResourceManager.GetObject("country00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap country01 {
            get {
                object obj = ResourceManager.GetObject("country01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap country1 {
            get {
                object obj = ResourceManager.GetObject("country1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap country2 {
            get {
                object obj = ResourceManager.GetObject("country2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap country3 {
            get {
                object obj = ResourceManager.GetObject("country3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap country4 {
            get {
                object obj = ResourceManager.GetObject("country4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap country5 {
            get {
                object obj = ResourceManager.GetObject("country5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap country6 {
            get {
                object obj = ResourceManager.GetObject("country6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap gvicon {
            get {
                object obj = ResourceManager.GetObject("gvicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon00 {
            get {
                object obj = ResourceManager.GetObject("memo_icon00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon01 {
            get {
                object obj = ResourceManager.GetObject("memo_icon01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon02 {
            get {
                object obj = ResourceManager.GetObject("memo_icon02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon03 {
            get {
                object obj = ResourceManager.GetObject("memo_icon03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon04 {
            get {
                object obj = ResourceManager.GetObject("memo_icon04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon05 {
            get {
                object obj = ResourceManager.GetObject("memo_icon05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon06 {
            get {
                object obj = ResourceManager.GetObject("memo_icon06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon07 {
            get {
                object obj = ResourceManager.GetObject("memo_icon07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon10 {
            get {
                object obj = ResourceManager.GetObject("memo_icon10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon11 {
            get {
                object obj = ResourceManager.GetObject("memo_icon11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon12 {
            get {
                object obj = ResourceManager.GetObject("memo_icon12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon13 {
            get {
                object obj = ResourceManager.GetObject("memo_icon13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon14 {
            get {
                object obj = ResourceManager.GetObject("memo_icon14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon15 {
            get {
                object obj = ResourceManager.GetObject("memo_icon15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon16 {
            get {
                object obj = ResourceManager.GetObject("memo_icon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon17 {
            get {
                object obj = ResourceManager.GetObject("memo_icon17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon18 {
            get {
                object obj = ResourceManager.GetObject("memo_icon18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon19 {
            get {
                object obj = ResourceManager.GetObject("memo_icon19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon20 {
            get {
                object obj = ResourceManager.GetObject("memo_icon20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを검색します. 
        /// </summary>
        internal static System.Drawing.Bitmap memo_icon21 {
            get {
                object obj = ResourceManager.GetObject("memo_icon21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
