//------------------------------------------------------------------------------
// <auto-generated>
//	 このコードはツールによって生成されました. 
//	 ランタイム 버전:4.0.30319.18444
//
//	 この파일への변경は, 以下の현황下で不正な動作の原因になったり, 
//	 コードが다시生成されるときに損失したりします. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace gvtrademap_cs.Properties {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
		
		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
		
		public static Settings Default {
			get {
				return defaultInstance;
			}
		}
	}
}
