//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました. 
//     ランタイム 버전:4.0.30319.18444
//
//     このファイルへの변경は, 以下の状況下で不正な動作の原因になったり, 
//     コードが再生成されるときに損失したりします. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace directx.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを검색するための, 厳密に型指定されたリソース クラスです. 
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを사용して自動生成されました. 
    // メンバーを追加または삭제するには, .ResX ファイルを編集して, /str オプションと共に
    // ResGen を実行し直すか, または VS プロジェクトをビルドし直します. 
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで사용されているキャッシュされた ResourceManager インスタンスを返します. 
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("directx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを사용して, 전부の검색リソースに対し, 
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします. 
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを검색します. 
        /// </summary>
        internal static byte[] sprite {
            get {
                object obj = ResourceManager.GetObject("sprite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを검색します. 
        /// </summary>
        internal static byte[] systemfont_8x16_ui_gothic {
            get {
                object obj = ResourceManager.GetObject("systemfont_8x16_ui_gothic", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
